[[pages]]
path = "pages/intro.py"
name = "IntroducciÃ³n"
icon = "ğŸ "

[[pages]]
path = "pages/datos.py"
name = "Sobre los datos"
icon = "ğŸ“ƒ"

[[pages]]
path = "pages/visual.py"
name = "VisualizaciÃ³n"
icon = "ğŸ‘€"

[[pages]]
path = "pages/formulario.py"
name = "Pruebas de formulario"
icon = "ğŸ“œ"